use rand::prelude::*;

// Array of quotes
const QUOTES: &[&str] = &[
    "A wizard may arrive later than expected, but rarely without reason.\n- Gandalf",
    "Courage is not the absence of fear; it is choosing to continue despite it.\n- Gandalf",
    "The smallest traveler may carry the greatest burden.\n- Gandalf",
    "Do not mistake darkness for the end of the road.\n- Gandalf",
    "Even when the path is hidden, the next step can still be taken.\n- Gandalf",
    "A great journey often begins with an unwanted interruption.\n- Bilbo",
    "There are adventures one chooses, and adventures that choose you.\n- Bilbo",
    "Home becomes precious when you have seen how vast the world can be.\n- Bilbo",
    "A comfortable chair can be difficult to leave, even for a worthy cause.\n- Bilbo",
    "Sometimes bravery begins with simply opening the door.\n- Bilbo",
    "The road beyond the hill may change everything you thought you knew.\n- Bilbo",
    "A quiet life can still hide a heart ready for adventure.\n- Bilbo",
    "You may leave home reluctantly and return with a completely different heart.\n- Bilbo",
    "The greatest treasures are not always the ones that glitter.\n- Bilbo",
    "A hobbit can surprise even himself when the moment demands it.\n- Bilbo",
    "There is more courage in an ordinary person than appearances suggest.\n- Bilbo",
    "A journey teaches lessons that books alone cannot provide.\n- Bilbo",
    "Sometimes the safest road is not the road worth taking.\n- Bilbo",
    "Adventure has a habit of arriving before breakfast.\n- Bilbo",
    "A ring may look insignificant while carrying consequences beyond measure.\n- Frodo",
    "The weight of a burden is not always measured in pounds.\n- Frodo",
    "Sometimes the only victory is refusing to give up.\n- Frodo",
    "The road becomes harder when you know how far you still have to go.\n- Frodo",
    "Even a frightened heart can choose to be brave.\n- Frodo",
    "No one should have to carry a terrible burden alone.\n- Frodo",
    "The darkness grows strongest when hope is abandoned.\n- Frodo",
    "There are journeys that change the person who began them.\n- Frodo",
    "A small hand can hold a burden meant for kings.\n- Frodo",
    "The world may feel impossibly large, but every journey is taken one step at a time.\n- Frodo",
    "Sometimes friendship is the only strength left when your own strength is gone.\n- Frodo",
    "A promise can become heavier than any chain.\n- Frodo",
    "The hardest road is sometimes the one that must be walked.\n- Frodo",
    "You cannot always choose the burden, but you can choose how you face it.\n- Frodo",
    "Even at the edge of despair, tomorrow may still be waiting.\n- Frodo",
    "A faithful companion can make an impossible road bearable.\n- Sam",
    "If your friend cannot take another step, sometimes you carry them.\n- Sam",
    "There is still goodness worth defending, even in a wounded world.\n- Sam",
    "A garden, a meal, and a peaceful home can be worth fighting for.\n- Sam",
    "Hope can survive in the smallest corner of the darkest place.\n- Sam",
    "You do not need to be fearless to stand beside someone you love.\n- Sam",
    "The journey may be terrible, but giving up can be worse.\n- Sam",
    "Sometimes loyalty means staying when everyone else has gone.\n- Sam",
    "A humble heart can accomplish things mighty warriors cannot.\n- Sam",
    "There are people who become heroes simply by refusing to abandon their friends.\n- Sam",
    "When the world grows dark, remember the things that make returning home worthwhile.\n- Sam",
    "A simple meal tastes better after a long and dangerous road.\n- Sam",
    "The promise of home can guide someone through terrible places.\n- Sam",
    "Friendship is not measured by how easy the road is.\n- Sam",
    "When courage fails, loyalty can carry you forward.\n- Sam",
    "A king is not made great by a crown alone.\n- Aragorn",
    "The strength to lead comes from knowing when to serve.\n- Aragorn",
    "A rightful ruler does not need to boast about his claim.\n- Aragorn",
    "The past may shape you without having to control your future.\n- Aragorn",
    "A broken kingdom can still be rebuilt.\n- Aragorn",
    "Sometimes a hidden heir must walk among ordinary people before taking his place.\n- Aragorn",
    "The sword matters less than the hand and heart that wield it.\n- Aragorn",
    "Leadership means walking into danger before asking others to follow.\n- Aragorn",
    "A king should carry responsibility more heavily than his crown.\n- Aragorn",
    "There are battles that must be fought because peace cannot be restored without them.\n- Aragorn",
    "Hope becomes powerful when someone is willing to act upon it.\n- Aragorn",
    "A warrior can be both fierce in battle and gentle in peace.\n- Aragorn",
    "The road to becoming a leader may begin with wandering.\n- Aragorn",
    "Honor is shown most clearly when nobody is watching.\n- Aragorn",
    "The future of a kingdom may depend on one person's willingness to return.\n- Aragorn",
    "A true king does not need to diminish others to prove his strength.\n- Aragorn",
    "Sometimes the old paths must be walked before new ones can be made.\n- Aragorn",
    "A sword reforged can become a symbol of a people restored.\n- Aragorn",
    "The courage to face one's lineage can be harder than facing an army.\n- Aragorn",
    "Even a ranger in the wilderness may carry the destiny of a kingdom.\n- Aragorn",
    "A warrior's skill is impressive, but loyalty makes it meaningful.\n- Legolas",
    "The world looks different from high above the forest floor.\n- Legolas",
    "Grace and speed can turn danger into opportunity.\n- Legolas",
    "An elf may see beauty where others see only ruin.\n- Legolas",
    "Friendship can cross the oldest rivalries.\n- Legolas",
    "A keen eye notices dangers long before they reach the camp.\n- Legolas",
    "The forest remembers things that cities have forgotten.\n- Legolas",
    "Even the swiftest warrior benefits from companions who challenge him.\n- Legolas",
    "A long-lived people still have much to learn from short-lived friends.\n- Legolas",
    "Sometimes an unlikely friendship becomes stronger than tradition.\n- Legolas",
    "Beauty and danger can exist in the same place.\n- Legolas",
    "The wilderness rewards those who pay attention.\n- Legolas",
    "A bow is only as useful as the judgment behind the arrow.\n- Legolas",
    "There is wisdom in observing before acting.\n- Legolas",
    "A fellowship becomes stronger when differences are accepted rather than erased.\n- Legolas",
    "A dwarf may be short in stature and enormous in stubbornness.\n- Gimli",
    "Old rivalries can become new friendships when danger arrives.\n- Gimli",
    "There is no shame in admitting that an enemy has earned your respect.\n- Gimli",
    "A sturdy axe and a stubborn heart can solve more problems than expected.\n- Gimli",
    "Dwarves remember what others would rather forget.\n- Gimli",
    "Gold can tempt even those who believe themselves immune to greed.\n- Gimli",
    "A warrior does not measure friendship by height or heritage.\n- Gimli",
    "Sometimes the fiercest companion is also the most dependable.\n- Gimli",
    "There are few things more satisfying than proving an old enemy wrong.\n- Gimli",
    "A good battle companion is worth more than a chest of treasure.\n- Gimli",
    "Even stubborn hearts can learn to trust.\n- Gimli",
    "Stone may endure for ages, but friendship can outlast stone.\n- Gimli",
    "A warrior's boast means little without the deeds to support it.\n- Gimli",
    "The best rival may eventually become your closest friend.\n- Gimli",
    "Some treasures are worth defending because they belong to an entire people.\n- Thorin",
    "A leader obsessed with reclaiming the past can lose sight of the people beside him.\n- Thorin",
    "A kingdom can be rebuilt with courage, but greed can destroy it from within.\n- Thorin",
    "Gold promises security while quietly demanding everything in return.\n- Thorin",
    "The mountain means more than its riches to those who call it home.\n- Thorin",
    "A king's greatest duty is to his people, not his treasure.\n- Thorin",
    "Pride can turn a rightful claim into a dangerous obsession.\n- Thorin",
    "The desire to reclaim what was lost can become a chain of its own.\n- Thorin",
    "A true victory is worth little if it costs the soul of the victor.\n- Thorin",
    "Sometimes the hardest battle is against the darkness growing inside yourself.\n- Thorin",
    "A crown cannot protect a heart consumed by greed.\n- Thorin",
    "The worth of a homeland cannot be measured in gold alone.\n- Thorin",
    "Even a proud king can discover that humility comes before redemption.\n- Thorin",
    "The greatest treasure may be realizing what should never have been sacrificed.\n- Thorin",
    "A kingdom needs more than walls; it needs people willing to care for one another.\n- Thorin",
    "The desire for gold can make familiar faces look like enemies.\n- Thorin",
    "A leader who remembers his purpose can find his way back from darkness.\n- Thorin",
    "Not every dragon's treasure is worth taking.\n- Thorin",
    "Power is dangerous when protecting it becomes more important than using it wisely.\n- Thorin",
    "A king's final legacy is measured in what he leaves behind in others.\n- Thorin",
    "A dragon's greatest weapon may be the fear it creates before it ever attacks.\n- Smaug",
    "Greed makes even an enormous treasure seem insufficient.\n- Smaug",
    "A creature surrounded by gold can still possess nothing worth loving.\n- Smaug",
    "Power can make an arrogant creature believe itself untouchable.\n- Smaug",
    "A clever opponent may survive by asking the right questions.\n- Smaug",
    "A weakness hidden beneath armor remains a weakness.\n- Smaug",
    "A dragon may know the value of gold without understanding the value of friendship.\n- Smaug",
    "Fear can make an enemy seem larger than it truly is.\n- Smaug",
    "A hoard can become a prison when its owner refuses to leave it.\n- Smaug",
    "Even the strongest creature can be undone by a small overlooked flaw.\n- Smaug",
    "Pride often makes dangerous creatures careless.\n- Smaug",
    "A sharp mind can be more dangerous than a sharp sword.\n- Smaug",
    "The greatest beast may still fall because of a single vulnerable place.\n- Smaug",
    "A monster's confidence can become its greatest weakness.\n- Smaug",
    "The possession of everything does not guarantee satisfaction.\n- Smaug",
    "Some beings cling to possessions because they have nothing else to call their own.\n- Gollum",
    "Obsession can turn a once-familiar object into the center of an entire existence.\n- Gollum",
    "A lonely creature may speak to itself because it has forgotten how to trust others.\n- Gollum",
    "Desire can become so strong that it consumes the person who feels it.\n- Gollum",
    "The past can follow someone even after their name and shape have changed.\n- Gollum",
    "Possession can become an addiction disguised as love.\n- Gollum",
    "A creature driven by hunger may still remember fragments of who it once was.\n- Gollum",
    "The smallest object can cast an enormous shadow over a life.\n- Gollum",
    "Trust is difficult when fear has become your constant companion.\n- Gollum",
    "An obsession rarely stays satisfied for long.\n- Gollum",
    "A beautiful object can hide an ugly influence.\n- Gollum",
    "Loneliness can twist the mind toward strange forms of comfort.\n- Gollum",
    "Even a broken creature may retain memories of a better self.\n- Gollum",
    "Desire becomes dangerous when it replaces every other purpose.\n- Gollum",
    "The things we possess can eventually begin to possess us.\n- Gollum",
    "Wisdom sometimes comes from knowing when to let go.\n- Galadriel",
    "Power is most dangerous when used without restraint.\n- Galadriel",
    "The future cannot always be seen clearly, even by those with great wisdom.\n- Galadriel",
    "A temptation may appear beautiful precisely because it promises everything.\n- Galadriel",
    "Mercy can be stronger than vengeance.\n- Galadriel",
    "The passing of an age does not mean that everything meaningful has been lost.\n- Galadriel",
    "Some endings are painful because they make room for something new.\n- Galadriel",
    "The world changes whether we are ready for it or not.\n- Galadriel",
    "True strength includes the ability to refuse power.\n- Galadriel",
    "Those who have great gifts must also carry great responsibility.\n- Galadriel",
    "Hope often survives in places where certainty cannot.\n- Galadriel",
    "The smallest act of mercy may alter a destiny.\n- Galadriel",
    "Beauty fades, but its memory can still guide the heart.\n- Galadriel",
    "Wisdom means understanding not only what you can do, but what you should refuse to do.\n- Galadriel",
    "Some doors must close so that another age can begin.\n- Galadriel",
    "A world in decline can still contain moments of extraordinary beauty.\n- Galadriel",
    "A ruler's first duty is to protect those who cannot protect themselves.\n- Théoden",
    "Fear can make a king forget the strength already standing around him.\n- Théoden",
    "A leader can recover after years of being guided by another's voice.\n- Théoden",
    "The courage of ordinary soldiers can restore the heart of a kingdom.\n- Théoden",
    "A king may be old and still find the strength to ride into battle.\n- Théoden",
    "Hope returns when people remember what they are fighting to preserve.\n- Théoden",
    "A ruler's honor is tested most severely when defeat seems inevitable.\n- Théoden",
    "The defense of home can unite people who once stood apart.\n- Théoden",
    "A final stand can have meaning even when victory seems distant.\n- Théoden",
    "The courage to face death can free a person from fear.\n- Théoden",
    "A kingdom survives through the courage of its people, not merely its walls.\n- Théoden",
    "A warrior can fight fiercely without surrendering compassion.\n- Éowyn",
    "Being underestimated can become a source of unexpected strength.\n- Éowyn",
    "A person's worth is not determined by the role others assign them.\n- Éowyn",
    "Courage can grow from years of being told to stay behind.\n- Éowyn",
    "Sometimes the person everyone overlooks is the one who changes the battle.\n- Éowyn",
    "A warrior's heart cannot always be confined by tradition.\n- Éowyn",
    "Freedom means having the chance to choose your own path.\n- Éowyn",
    "Fear does not erase courage; it gives courage something to overcome.\n- Éowyn",
    "A shield can represent both protection and defiance.\n- Éowyn",
    "The strongest answer to doubt is sometimes action.\n- Éowyn",
    "A person can step beyond the expectations placed upon them.\n- Éowyn",
    "Fate may offer a path, but courage determines how it is walked.\n- Éowyn",
    "There are battles where identity matters less than the will to stand.\n- Éowyn",
    "The world is wider than the role others have written for you.\n- Éowyn",
    "A warrior's strength is not diminished by compassion.\n- Éowyn",
    "A creature rooted in the earth can become a powerful guardian of the living world.\n- Treebeard",
    "Trees remember slowly, but they remember deeply.\n- Treebeard",
    "Hasty decisions often cause problems that patience would have prevented.\n- Treebeard",
    "The forest is not empty simply because humans do not understand its voices.\n- Treebeard",
    "Ancient things may move slowly while still possessing enormous strength.\n- Treebeard",
    "Nature has its own time, and not everything should be rushed.\n- Treebeard",
    "The destruction of forests is also the destruction of memories and homes.\n- Treebeard",
    "Sometimes the quietest beings are stirred only when something precious is threatened.\n- Treebeard",
    "Patience is not weakness; it is strength waiting for the right moment.\n- Treebeard",
    "An old forest can outlast many generations of its enemies.\n- Treebeard",
    "The natural world has consequences for those who treat it carelessly.\n- Treebeard",
    "Ancient wisdom may require time before it is understood.\n- Treebeard",
    "The earth does not hurry, yet it changes everything.\n- Treebeard",
    "A people forgotten by history may still rise when their home is threatened.\n- Treebeard",
    "The strongest roots are often the ones nobody notices.\n- Treebeard",
    "A peaceful forest can become formidable when pushed too far.\n- Treebeard",
    "There are enemies who cannot understand the things they destroy.\n- Treebeard",
    "A journey through darkness makes ordinary daylight feel extraordinary.\n- The Fellowship",
    "The strength of a fellowship comes from people who bring different gifts to the same purpose.\n- The Fellowship",
    "No single member needs to possess every strength when companions can share the burden.\n- The Fellowship",
    "Trust is built one difficult decision at a time.\n- The Fellowship",
    "A fellowship can survive disagreement when its members remember what brought them together.\n- The Fellowship",
    "The road is less frightening when walked with people who refuse to abandon you.\n- The Fellowship",
    "Great quests are rarely completed by great people alone.\n- The Fellowship",
    "Unity does not require everyone to be alike.\n- The Fellowship",
    "Different peoples can stand together when faced with a common darkness.\n- The Fellowship",
    "Friendship can accomplish what strength alone cannot.\n- The Fellowship",
    "Every companion carries a different piece of the hope needed for the journey.\n- The Fellowship",
    "A broken fellowship does not necessarily mean a broken purpose.\n- The Fellowship",
    "Even after companions separate, their shared purpose can continue.\n- The Fellowship",
    "The road divides people without necessarily ending their friendship.\n- The Fellowship",
    "A fellowship is tested not when everything is easy, but when trust becomes difficult.\n- The Fellowship",
    "The strongest bonds are often formed far from home.\n- The Fellowship",
    "Hope can be kept alive by people who refuse to surrender it.\n- The Fellowship",
    "The world can be saved by ordinary people making extraordinary choices.\n- The Fellowship",
    "Darkness may spread quickly, but courage can travel just as far.\n- The Fellowship",
    "The smallest act of kindness can become important long after it is forgotten.\n- The Fellowship",
    "A journey worth taking is rarely a journey without danger.\n- The Fellowship",
];

// Choosing a random quote
pub fn random() -> String {
    QUOTES.choose(&mut rand::rng()).unwrap().to_string()
}
